power <- read.delim("household_power_consumption.txt", sep = ";", header = T, stringsAsFactors = F)
pdata <- subset(power, power$Date=="1/2/2007" | power$Date=="2/2/2007" )
new <- paste(pdata$Date, pdata$Time, sep = " ")
pdata$newD <- strptime(new, format = "%d/%m/%Y %H:%M:%S")
png(filename = "Plot3.png", width = 480, height = 480)
plot(pdata$newD, as.numeric(pdata$Sub_metering_1), xlab = "", ylab = "Energy sub metering", type = "n")
points(pdata$newD, as.numeric(pdata$Sub_metering_1), type = "l")
points(pdata$newD, as.numeric(pdata$Sub_metering_2), type = "l", col="red")
points(pdata$newD, as.numeric(pdata$Sub_metering_3), type = "l", col="blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()